version: "3.7"
services:
  datascience-workspace:
    image: jupyter/datascience-notebook:python-3.8.6
    environment:
      - JUPYTER_TOKEN=password
    volumes:
      - ./:/home/jovyan/work
    ports:
      - 8888:8888
    container_name: datascience-workspace
